version: 2.1
orbs:
  node: circleci/node@5.0.2
  heroku: circleci/heroku@1.2.6
workflows:
  test-and-deploy:
    jobs:
      - build
        run:
          command: npm run build:staging
      - node/test
        requires:
          - build
      - heroku/deploy-via-git:
          filters:
            branches:
              only:
                - main
          requires:
            - node/test
