version: 2.1
orbs:
  node: circleci/node@5.0.2
  heroku: circleci/heroku@1.2.6
workflows:
  test-and-deploy:
    jobs:
      deploy:
        executor: heroku/default
        steps:
          - checkout
          - heroku/install
          - run:
              command: npm run build:staging
          - node/test
          - heroku/deploy-via-git:
              filters:
                branches:
                  only:
                    - main
                
