# version: 2.1
# orbs:
#   node: circleci/node@5.0.2
#   heroku: circleci/heroku@1.2.6
# workflows:
#   test-and-deploy:
#     jobs:
#       deploy:
#         executor: heroku/default
#         steps:
#           - checkout
#           - heroku/install
#           - run:
#               command: npm run build:staging
#           - node/test
#           - heroku/deploy-via-git:
#               filters:
#                 branches:
#                   only:
#                     - main
                
version: 2.1
orbs:
  node: circleci/node@5.0.2
  heroku: circleci/heroku@1.2.6
jobs:
  build-and-test:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - node/install:
          node-version: "12.22"
      - node/install-packages
      - run:
          command: npm run test
  deploy-to-stage:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - node/install:
          node-version: "12.22"
      - node/install-packages
      - run:
          command: npm run build:staging
      - heroku/deploy-via-git:
          filters:
            branches:
              only:
                - main
    requires:
      - build
workflows:
  build-and-test:
    jobs:
      - build-and-test
      - deploy-to-stage